// Auto-generated from kaarten.json
const ALL_CARDS = [
  {
    id: 1,
    naam: 'Thales van Milete',
    geboren: -624,
    overleden: -546,
    stroming: 'Oudheid',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer'],
    vp: 3,
    boek_capaciteit: 1,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee uit de voorraad.',
    citaat: 'Alles is water.'
  },
  {
    id: 2,
    naam: 'Anaximander',
    geboren: -610,
    overleden: -546,
    stroming: 'Oudheid',
    traditie: 'empirisch',
    invloed: 3,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer'],
    vp: 3,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 willekeurig idee uit de Bibliotheek.',
    citaat: 'Het onbegrensde is het begin van alle dingen.'
  },
  {
    id: 3,
    naam: 'Pythagoras',
    geboren: -570,
    overleden: -495,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'sfeer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Als je minstens 2 Passer-filosofen hebt, pak 1 extra idee.',
    citaat: 'Alles is getal.'
  },
  {
    id: 4,
    naam: 'Heraclitus',
    geboren: -535,
    overleden: -475,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer'],
    vp: 4,
    boek_capaciteit: 1,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Hergooi alle dobbelstenen in de Bibliotheek.',
    citaat: 'Alles stroomt.'
  },
  {
    id: 5,
    naam: 'Parmenides',
    geboren: -515,
    overleden: -450,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'passer'],
    vp: 6,
    boek_capaciteit: 1,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Trek 2 kaarten uit de stapel.',
    citaat: 'Wat is, is. Wat niet is, is niet.'
  },
  {
    id: 6,
    naam: 'Socrates',
    geboren: -469,
    overleden: -399,
    stroming: 'Oudheid',
    traditie: 'dialectisch',
    invloed: 8,
    vaardigheden: ['Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 7,
    boek_capaciteit: 0,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler een filosoof aanspeelt, mag jij 1 kaart trekken.',
    citaat: 'Ik weet dat ik niets weet.'
  },
  {
    id: 7,
    naam: 'Plato',
    geboren: -428,
    overleden: -348,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 9,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'weegschaal', 'passer'],
    vp: 9,
    boek_capaciteit: 5,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart uit de open rij onder deze filosoof.',
    citaat: 'De maat van alle dingen is de Idee.'
  },
  {
    id: 8,
    naam: 'Aristoteles',
    geboren: -384,
    overleden: -322,
    stroming: 'Oudheid',
    traditie: 'eclectisch',
    invloed: 9,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'passer', 'sfeer'],
    vp: 9,
    boek_capaciteit: 6,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op een willekeurige filosoof in je Academie.',
    citaat: 'De mens is van nature een politiek dier.'
  },
  {
    id: 9,
    naam: 'Diogenes van Sinope',
    geboren: -412,
    overleden: -323,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['Sp'],
    kosten: [],
    vp: 2,
    boek_capaciteit: 0,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler 3+ ideeen pakt, verwijder 1 idee uit de Bibliotheek.',
    citaat: 'Ga uit mijn zonlicht.'
  },
  {
    id: 10,
    naam: 'Epicurus',
    geboren: -341,
    overleden: -270,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee uit de voorraad.',
    citaat: 'De dood gaat ons niet aan.'
  },
  {
    id: 11,
    naam: 'Zeno van Citium',
    geboren: -334,
    overleden: -262,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Als je geen ideeen hebt, pak er 2 willekeurige.',
    citaat: 'Het geluk is een goede stroom van het leven.'
  },
  {
    id: 12,
    naam: 'Cicero',
    geboren: -106,
    overleden: -43,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'oog'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart en leg 1 boek.',
    citaat: 'De wetten zwijgen te midden van wapens.'
  },
  {
    id: 13,
    naam: 'Seneca',
    geboren: -4,
    overleden: 65,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee naar keuze uit de Bibliotheek.',
    citaat: 'Het is niet dat we weinig tijd hebben, maar dat we er veel verspillen.'
  },
  {
    id: 14,
    naam: 'Epictetus',
    geboren: 50,
    overleden: 135,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['Sp'],
    kosten: ['spiegel'],
    vp: 3,
    boek_capaciteit: 0,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler ideeen verliest, mag jij 1 idee pakken.',
    citaat: 'Het zijn niet de dingen die ons verontrusten, maar onze oordelen erover.'
  },
  {
    id: 15,
    naam: 'Marcus Aurelius',
    geboren: 121,
    overleden: 180,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op deze kaart als je minstens 3 filosofen hebt.',
    citaat: 'Je hebt macht over je geest, niet over uiterlijke gebeurtenissen.'
  },
  {
    id: 16,
    naam: 'Plotinus',
    geboren: 204,
    overleden: 270,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'sfeer'],
    vp: 7,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 Sfeer-ideeen uit de voorraad.',
    citaat: 'Het Ene is alles en niets.'
  },
  {
    id: 17,
    naam: 'Hypatia',
    geboren: 360,
    overleden: 415,
    stroming: 'Oudheid',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'oog'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Pak 1 Passer- en 1 Oog-idee uit de voorraad.',
    citaat: 'Bewaar je recht om te denken.'
  },
  {
    id: 18,
    naam: 'Augustinus',
    geboren: 354,
    overleden: 430,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'weegschaal'],
    vp: 7,
    boek_capaciteit: 5,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart van de stapel onder deze filosoof.',
    citaat: 'Geloof opdat gij moogt begrijpen.'
  },
  {
    id: 19,
    naam: 'Boethius',
    geboren: 477,
    overleden: 524,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'sfeer'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 willekeurig idee als je minstens 2 boeken hebt.',
    citaat: 'De filosofie is de troost.'
  },
  {
    id: 20,
    naam: 'Anselmus van Canterbury',
    geboren: 1033,
    overleden: 1109,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Trek 2 kaarten en houd er 1.',
    citaat: 'Ik geloof opdat ik mag begrijpen.'
  },
  {
    id: 21,
    naam: 'Peter Abelardus',
    geboren: 1079,
    overleden: 1142,
    stroming: 'Middeleeuwen',
    traditie: 'dialectisch',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer'],
    vp: 3,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Passer-idee uit de voorraad.',
    citaat: 'Door te twijfelen komen we tot onderzoek.'
  },
  {
    id: 22,
    naam: 'Averroes (Ibn Rushd)',
    geboren: 1126,
    overleden: 1198,
    stroming: 'Middeleeuwen',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'passer'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart als je een Oudheid-filosoof hebt.',
    citaat: 'Onwetendheid leidt tot angst.'
  },
  {
    id: 23,
    naam: 'Maimonides',
    geboren: 1138,
    overleden: 1204,
    stroming: 'Middeleeuwen',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'sfeer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal- of 1 Sfeer-idee naar keuze.',
    citaat: 'Geef een mens een vis en hij eet een dag. Leer hem vissen en hij eet een leven lang.'
  },
  {
    id: 24,
    naam: 'Thomas van Aquino',
    geboren: 1225,
    overleden: 1274,
    stroming: 'Middeleeuwen',
    traditie: 'empirisch',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'weegschaal', 'passer'],
    vp: 9,
    boek_capaciteit: 5,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op deze kaart en pak 1 idee.',
    citaat: 'Het doel van het leven is de gelukzaligheid.'
  },
  {
    id: 25,
    naam: 'William van Ockham',
    geboren: 1287,
    overleden: 1347,
    stroming: 'Middeleeuwen',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['passer'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Verwijder 1 kosten-idee van een filosoof in je hand (maak goedkoper).',
    citaat: 'Entiteiten moeten niet onnodig vermenigvuldigd worden.'
  },
  {
    id: 26,
    naam: 'Nicolo Machiavelli',
    geboren: 1469,
    overleden: 1527,
    stroming: 'Renaissance',
    traditie: 'normatief',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler een filosoof aanspeelt, mag jij 1 idee uit de Bibliotheek pakken.',
    citaat: 'Het doel heiligt de middelen.'
  },
  {
    id: 27,
    naam: 'Erasmus',
    geboren: 1466,
    overleden: 1536,
    stroming: 'Renaissance',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'weegschaal'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart uit de open rij.',
    citaat: 'In het land der blinden is eenoog koning.'
  },
  {
    id: 28,
    naam: 'Thomas More',
    geboren: 1478,
    overleden: 1535,
    stroming: 'Renaissance',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op deze kaart.',
    citaat: 'Utopia is nergens en overal.'
  },
  {
    id: 29,
    naam: 'Michel de Montaigne',
    geboren: 1533,
    overleden: 1592,
    stroming: 'Renaissance',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'oog'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart van de stapel onder deze filosoof.',
    citaat: 'Que sais-je? - Wat weet ik?'
  },
  {
    id: 30,
    naam: 'Francis Bacon',
    geboren: 1561,
    overleden: 1626,
    stroming: 'Renaissance',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'passer'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee uit de voorraad.',
    citaat: 'Kennis is macht.'
  },
  {
    id: 31,
    naam: 'Thomas Hobbes',
    geboren: 1588,
    overleden: 1679,
    stroming: 'Rationalisme',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Alle spelers verliezen 1 idee naar keuze (jij niet).',
    citaat: 'Het leven is eenzaam, armoedig, gemeen, beestachtig en kort.'
  },
  {
    id: 32,
    naam: 'Rene Descartes',
    geboren: 1596,
    overleden: 1650,
    stroming: 'Rationalisme',
    traditie: 'contemplatief',
    invloed: 8,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'sfeer', 'oog'],
    vp: 8,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee naar keuze uit de Bibliotheek en trek 1 kaart.',
    citaat: 'Ik denk, dus ik ben.'
  },
  {
    id: 33,
    naam: 'Baruch Spinoza',
    geboren: 1632,
    overleden: 1677,
    stroming: 'Rationalisme',
    traditie: 'contemplatief',
    invloed: 7,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer', 'weegschaal'],
    vp: 9,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 ideeen naar keuze uit de Bibliotheek.',
    citaat: 'God of de Natuur.'
  },
  {
    id: 34,
    naam: 'Gottfried Wilhelm Leibniz',
    geboren: 1646,
    overleden: 1716,
    stroming: 'Rationalisme',
    traditie: 'eclectisch',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'sfeer', 'oog'],
    vp: 8,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart onder deze filosoof en pak 1 idee.',
    citaat: 'Dit is de beste van alle mogelijke werelden.'
  },
  {
    id: 35,
    naam: 'Blaise Pascal',
    geboren: 1623,
    overleden: 1662,
    stroming: 'Rationalisme',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Kijk naar de bovenste 3 kaarten van de stapel. Houd er 1, leg de rest terug.',
    citaat: 'Het hart heeft redenen die de rede niet kent.'
  },
  {
    id: 36,
    naam: 'John Locke',
    geboren: 1632,
    overleden: 1704,
    stroming: 'Empirisme',
    traditie: 'empirisch',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'weegschaal'],
    vp: 7,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog- en 1 Weegschaal-idee uit de voorraad.',
    citaat: 'De geest is een onbeschreven blad.'
  },
  {
    id: 37,
    naam: 'George Berkeley',
    geboren: 1685,
    overleden: 1753,
    stroming: 'Empirisme',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'oog'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwissel 1 idee met 1 idee in de Bibliotheek.',
    citaat: 'Zijn is waargenomen worden.'
  },
  {
    id: 38,
    naam: 'David Hume',
    geboren: 1711,
    overleden: 1776,
    stroming: 'Empirisme',
    traditie: 'empirisch',
    invloed: 8,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'oog', 'passer'],
    vp: 8,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 Oog-ideeen en trek 1 kaart.',
    citaat: 'De rede is de slaaf van de hartstochten.'
  },
  {
    id: 39,
    naam: 'Voltaire',
    geboren: 1694,
    overleden: 1778,
    stroming: 'Verlichting',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'oog'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler een kaart trekt, mag jij ook 1 kaart trekken.',
    citaat: 'Ik ben het niet eens met wat u zegt, maar ik zal uw recht om het te zeggen verdedigen.'
  },
  {
    id: 40,
    naam: 'Jean-Jacques Rousseau',
    geboren: 1712,
    overleden: 1778,
    stroming: 'Verlichting',
    traditie: 'normatief',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 7,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op deze kaart en pak 1 Weegschaal-idee.',
    citaat: 'De mens wordt vrij geboren, maar is overal in ketenen.'
  },
  {
    id: 41,
    naam: 'Montesquieu',
    geboren: 1689,
    overleden: 1755,
    stroming: 'Verlichting',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee voor elke 2 filosofen in je Lezen-rij.',
    citaat: 'Vrijheid is het recht om te doen wat de wet toestaat.'
  },
  {
    id: 42,
    naam: 'Denis Diderot',
    geboren: 1713,
    overleden: 1784,
    stroming: 'Verlichting',
    traditie: 'eclectisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'passer'],
    vp: 6,
    boek_capaciteit: 5,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op elke filosoof in je Schrijven-rij die nog ruimte heeft.',
    citaat: 'De mens zal nooit vrij zijn totdat de laatste koning is gewurgd met de ingewanden van de laatste priester.'
  },
  {
    id: 43,
    naam: 'Immanuel Kant',
    geboren: 1724,
    overleden: 1804,
    stroming: 'Verlichting',
    traditie: 'normatief',
    invloed: 9,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'oog', 'passer', 'sfeer'],
    vp: 12,
    boek_capaciteit: 5,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee van elk symbooltype (max 1 per type) uit de voorraad.',
    citaat: 'Durf te denken!'
  },
  {
    id: 44,
    naam: 'Adam Smith',
    geboren: 1723,
    overleden: 1790,
    stroming: 'Verlichting',
    traditie: 'empirisch',
    invloed: 7,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler ideeen uit de Bibliotheek pakt, pak jij er ook 1.',
    citaat: 'Het is niet uit welwillendheid van de slager dat wij ons avondeten verwachten.'
  },
  {
    id: 45,
    naam: 'Mary Wollstonecraft',
    geboren: 1759,
    overleden: 1797,
    stroming: 'Verlichting',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee voor elke vrouwelijke filosoof in je Academie.',
    citaat: 'Ik wil niet dat vrouwen macht hebben over mannen, maar over zichzelf.'
  },
  {
    id: 46,
    naam: 'Johann Gottlieb Fichte',
    geboren: 1762,
    overleden: 1814,
    stroming: 'Duits Idealisme',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'spiegel'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee en leg 1 boek.',
    citaat: 'Het Ik stelt zichzelf.'
  },
  {
    id: 47,
    naam: 'Friedrich Schelling',
    geboren: 1775,
    overleden: 1854,
    stroming: 'Duits Idealisme',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'oog'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 ideeen waarvan minstens 1 Sfeer.',
    citaat: 'De natuur is de zichtbare geest, de geest de onzichtbare natuur.'
  },
  {
    id: 48,
    naam: 'Georg Wilhelm Friedrich Hegel',
    geboren: 1770,
    overleden: 1831,
    stroming: 'Duits Idealisme',
    traditie: 'dialectisch',
    invloed: 9,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'passer', 'spiegel'],
    vp: 10,
    boek_capaciteit: 5,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart uit je hand onder deze filosoof en pak 2 ideeen.',
    citaat: 'Het werkelijke is redelijk en het redelijke is werkelijk.'
  },
  {
    id: 49,
    naam: 'Arthur Schopenhauer',
    geboren: 1788,
    overleden: 1860,
    stroming: 'Duits Idealisme',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 boek van een medespeler naar de voorraad en leg 1 boek bij jezelf.',
    citaat: 'De wereld is mijn voorstelling.'
  },
  {
    id: 50,
    naam: 'Karl Marx',
    geboren: 1818,
    overleden: 1883,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 9,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel', 'oog'],
    vp: 9,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Alle spelers geven 1 idee door aan de speler links van hen.',
    citaat: 'De filosofen hebben de wereld slechts geinterpreteerd; het komt erop aan haar te veranderen.'
  },
  {
    id: 51,
    naam: 'Friedrich Engels',
    geboren: 1820,
    overleden: 1895,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'oog'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Als Marx in je Academie ligt, pak 2 extra ideeen.',
    citaat: 'Alles wat bestaat verdient ten gronde te gaan.'
  },
  {
    id: 52,
    naam: 'John Stuart Mill',
    geboren: 1806,
    overleden: 1873,
    stroming: 'Empirisme',
    traditie: 'normatief',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'oog'],
    vp: 7,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee en trek 1 kaart.',
    citaat: 'Over zichzelf, over zijn eigen lichaam en geest, is het individu soeverein.'
  },
  {
    id: 53,
    naam: 'Soren Kierkegaard',
    geboren: 1813,
    overleden: 1855,
    stroming: 'Existentialisme',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'sfeer'],
    vp: 7,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart van de stapel. Als het een Existentialisme-filosoof is, citeer er nog 1.',
    citaat: 'Het leven kan alleen achterwaarts begrepen worden, maar moet voorwaarts geleefd worden.'
  },
  {
    id: 54,
    naam: 'Friedrich Nietzsche',
    geboren: 1844,
    overleden: 1900,
    stroming: 'Existentialisme',
    traditie: 'contemplatief',
    invloed: 8,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'sfeer', 'weegschaal'],
    vp: 9,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 filosoof van het open aanbod en citeer die kaart onder Nietzsche.',
    citaat: 'God is dood.'
  },
  {
    id: 55,
    naam: 'Charles Sanders Peirce',
    geboren: 1839,
    overleden: 1914,
    stroming: 'Pragmatisme',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'oog'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Passer- of 1 Oog-idee naar keuze.',
    citaat: 'De essentie van geloof is het vestigen van een gewoonte.'
  },
  {
    id: 56,
    naam: 'William James',
    geboren: 1842,
    overleden: 1910,
    stroming: 'Pragmatisme',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwissel tot 2 ideeen met de Bibliotheek.',
    citaat: 'Het waar is alleen het gunstige in ons denken.'
  },
  {
    id: 57,
    naam: 'John Dewey',
    geboren: 1859,
    overleden: 1952,
    stroming: 'Pragmatisme',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'weegschaal'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek en pak 1 idee naar keuze.',
    citaat: 'Onderwijs is niet voorbereiding op het leven; onderwijs is het leven zelf.'
  },
  {
    id: 58,
    naam: 'Edmund Husserl',
    geboren: 1859,
    overleden: 1938,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 7,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'sfeer', 'passer'],
    vp: 8,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Kijk naar de bovenste 5 kaarten van de stapel. Neem er 1 en leg de rest terug.',
    citaat: 'Terug naar de zaken zelf!'
  },
  {
    id: 59,
    naam: 'Martin Heidegger',
    geboren: 1889,
    overleden: 1976,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 7,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'spiegel', 'passer'],
    vp: 9,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer- en 1 Spiegel-idee. Citeer 1 kaart.',
    citaat: 'De taal is het huis van het Zijn.'
  },
  {
    id: 60,
    naam: 'Jean-Paul Sartre',
    geboren: 1905,
    overleden: 1980,
    stroming: 'Existentialisme',
    traditie: 'contemplatief',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'spiegel', 'weegschaal'],
    vp: 9,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 idee om 2 kaarten te trekken. Citeer 1 kaart.',
    citaat: 'De existentie gaat vooraf aan de essentie.'
  },
  {
    id: 61,
    naam: 'Simone de Beauvoir',
    geboren: 1908,
    overleden: 1986,
    stroming: 'Existentialisme',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal', 'sfeer'],
    vp: 9,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Spiegel-idee voor elke vrouwelijke filosoof in je Academie.',
    citaat: 'Je wordt niet als vrouw geboren, je wordt vrouw gemaakt.'
  },
  {
    id: 62,
    naam: 'Albert Camus',
    geboren: 1913,
    overleden: 1960,
    stroming: 'Existentialisme',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal'],
    vp: 7,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart. Als het een Existentialisme-filosoof is, trek er nog 1.',
    citaat: 'Men moet zich Sisyphus als een gelukkig mens voorstellen.'
  },
  {
    id: 63,
    naam: 'Hannah Arendt',
    geboren: 1906,
    overleden: 1975,
    stroming: 'Kritische Theorie',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel', 'oog'],
    vp: 9,
    boek_capaciteit: 4,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler de Spreken-rij activeert, mag jij 1 kaart trekken.',
    citaat: 'De banaliteit van het kwaad.'
  },
  {
    id: 64,
    naam: 'Ludwig Wittgenstein',
    geboren: 1889,
    overleden: 1951,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 8,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'passer', 'oog'],
    vp: 10,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Hergooi alle Bibliotheek-dobbelstenen. Pak 2 Passer-ideeen.',
    citaat: 'Waarover men niet spreken kan, daarover moet men zwijgen.'
  },
  {
    id: 65,
    naam: 'Bertrand Russell',
    geboren: 1872,
    overleden: 1970,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'oog', 'weegschaal'],
    vp: 9,
    boek_capaciteit: 5,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 ideeen naar keuze en trek 1 kaart.',
    citaat: 'Het hele probleem met de wereld is dat dwazen vol zelfvertrouwen zijn.'
  },
  {
    id: 66,
    naam: 'Gottlob Frege',
    geboren: 1848,
    overleden: 1925,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'passer'],
    vp: 6,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 Passer-ideeen uit de voorraad.',
    citaat: 'Een definitie van een begrip moet vruchtbaar zijn.'
  },
  {
    id: 67,
    naam: 'Alfred North Whitehead',
    geboren: 1861,
    overleden: 1947,
    stroming: 'Analytische Filosofie',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee en leg 1 boek.',
    citaat: 'De veiligste algemene karakterisering van de Europese filosofische traditie is dat ze een reeks voetnoten bij Plato is.'
  },
  {
    id: 68,
    naam: 'Karl Popper',
    geboren: 1902,
    overleden: 1994,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'passer'],
    vp: 7,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 kaart uit de open rij en trek 2 kaarten van de stapel.',
    citaat: 'Een theorie die niet weerlegbaar is, is niet wetenschappelijk.'
  },
  {
    id: 69,
    naam: 'Rudolf Carnap',
    geboren: 1891,
    overleden: 1970,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'oog'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Kijk naar 3 kaarten van de stapel, houd 1.',
    citaat: 'De logica van de wetenschap vervangt de filosofie.'
  },
  {
    id: 70,
    naam: 'W.V.O. Quine',
    geboren: 1908,
    overleden: 2000,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Passer-idee. Als je 3+ Analytische Filosofie-kaarten hebt, pak er 2.',
    citaat: 'Zijn is de waarde van een variabele zijn.'
  },
  {
    id: 71,
    naam: 'Theodor Adorno',
    geboren: 1903,
    overleden: 1969,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'weegschaal', 'oog'],
    vp: 8,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart. Als het een Kritische Theorie-filosoof is, pak 1 extra idee.',
    citaat: 'Na Auschwitz een gedicht schrijven is barbaars.'
  },
  {
    id: 72,
    naam: 'Max Horkheimer',
    geboren: 1895,
    overleden: 1973,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'oog'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee. Als Adorno in je Academie ligt, pak 1 extra.',
    citaat: 'Wie over kapitalisme niet wil spreken, moet ook over fascisme zwijgen.'
  },
  {
    id: 73,
    naam: 'Herbert Marcuse',
    geboren: 1898,
    overleden: 1979,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler boeken legt, mag jij 1 boek leggen.',
    citaat: 'De bevrijding van de mens is geen uitnodiging tot luiheid.'
  },
  {
    id: 74,
    naam: 'Jurgen Habermas',
    geboren: 1929,
    overleden: null,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'passer', 'spiegel'],
    vp: 9,
    boek_capaciteit: 4,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler de Spreken-rij activeert, pak jij 1 idee naar keuze.',
    citaat: 'De ideale gesprekssituatie.'
  },
  {
    id: 75,
    naam: 'Michel Foucault',
    geboren: 1926,
    overleden: 1984,
    stroming: 'Postmodernisme',
    traditie: 'dialectisch',
    invloed: 8,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal', 'oog'],
    vp: 9,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 filosoof uit de open rij. Citeer die kaart en pak 1 idee.',
    citaat: 'Waar macht is, is weerstand.'
  },
  {
    id: 76,
    naam: 'Jacques Derrida',
    geboren: 1930,
    overleden: 2004,
    stroming: 'Postmodernisme',
    traditie: 'contemplatief',
    invloed: 7,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'spiegel', 'sfeer'],
    vp: 8,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Neem 1 kaart van onder een medespelers filosoof en citeer die onder jouw filosoof.',
    citaat: 'Er is niets buiten de tekst.'
  },
  {
    id: 77,
    naam: 'Gilles Deleuze',
    geboren: 1925,
    overleden: 1995,
    stroming: 'Postmodernisme',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'spiegel'],
    vp: 7,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee en verplaats 1 filosoof naar een andere rij.',
    citaat: 'Het verschil is de ware oorsprong.'
  },
  {
    id: 78,
    naam: 'Jean-Francois Lyotard',
    geboren: 1924,
    overleden: 1998,
    stroming: 'Postmodernisme',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Verwijder 1 Paradigmaverschuiving-tegel en onthul een nieuwe.',
    citaat: 'Het einde van de grote verhalen.'
  },
  {
    id: 79,
    naam: 'Richard Rorty',
    geboren: 1931,
    overleden: 2007,
    stroming: 'Pragmatisme',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwissel 1 filosoof in je hand met 1 uit de open rij.',
    citaat: 'De waarheid is gemaakt, niet gevonden.'
  },
  {
    id: 80,
    naam: 'Slavoj Zizek',
    geboren: 1949,
    overleden: null,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal'],
    vp: 5,
    boek_capaciteit: 4,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler een kaart citeert, mag jij 1 kaart trekken.',
    citaat: 'De ware utopie is geloven dat het huidige systeem oneindig kan doorgaan.'
  },
  {
    id: 81,
    naam: 'Maurice Merleau-Ponty',
    geboren: 1908,
    overleden: 1961,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog- en 1 Spiegel-idee.',
    citaat: 'Het lichaam is ons middel om een wereld te hebben.'
  },
  {
    id: 82,
    naam: 'Emmanuel Levinas',
    geboren: 1906,
    overleden: 1995,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel', 'sfeer'],
    vp: 8,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee voor elke filosoof in je Spreken-rij.',
    citaat: 'Het gelaat van de Ander gebiedt: gij zult niet doden.'
  },
  {
    id: 83,
    naam: 'Paul Ricoeur',
    geboren: 1913,
    overleden: 2005,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'spiegel'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart en trek 1 kaart.',
    citaat: 'Het symbool geeft te denken.'
  },
  {
    id: 84,
    naam: 'Hans-Georg Gadamer',
    geboren: 1900,
    overleden: 2002,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'passer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart. Als je 2+ Fenomenologie-filosofen hebt, trek er 2.',
    citaat: 'Begrijpen is altijd anders begrijpen.'
  },
  {
    id: 85,
    naam: 'Simone Weil',
    geboren: 1909,
    overleden: 1943,
    stroming: 'Existentialisme',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 van je ideeen. Pak 3 ideeen naar keuze.',
    citaat: 'Aandacht is de zeldzaamste en puurste vorm van vrijgevigheid.'
  },
  {
    id: 86,
    naam: 'John Rawls',
    geboren: 1921,
    overleden: 2002,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'weegschaal', 'passer'],
    vp: 9,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verdeel 3 ideeen eerlijk over alle spelers (jij eerst).',
    citaat: 'Rechtvaardigheid is de eerste deugd van sociale instituties.'
  },
  {
    id: 87,
    naam: 'Robert Nozick',
    geboren: 1938,
    overleden: 2002,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'passer'],
    vp: 6,
    boek_capaciteit: 2,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler ideeen herverdelt, mag jij weigeren en 1 extra idee pakken.',
    citaat: 'Het individu is onschendbaar.'
  },
  {
    id: 88,
    naam: 'Martha Nussbaum',
    geboren: 1947,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel', 'oog'],
    vp: 8,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee per uniek symbooltype in je Academie.',
    citaat: 'Emoties zijn vormen van waardeoordelen.'
  },
  {
    id: 89,
    naam: 'Peter Singer',
    geboren: 1946,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler ideeen verspilt, pak jij 1 idee.',
    citaat: 'Als we het in onze macht hebben iets ergs te voorkomen, moeten we het doen.'
  },
  {
    id: 90,
    naam: 'Judith Butler',
    geboren: 1956,
    overleden: null,
    stroming: 'Feminisme',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'spiegel', 'weegschaal'],
    vp: 8,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verplaats 1 filosoof naar een andere rij en pak 2 ideeen.',
    citaat: 'Gender is performatief.'
  },
  {
    id: 91,
    naam: 'Iris Murdoch',
    geboren: 1919,
    overleden: 1999,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek en citeer 1 kaart.',
    citaat: 'Liefde is de moeilijke realisatie dat iets anders dan jijzelf werkelijk is.'
  },
  {
    id: 92,
    naam: 'Philippa Foot',
    geboren: 1920,
    overleden: 2010,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Alle spelers kiezen: betaal 1 idee of verlies 1 boek.',
    citaat: 'Het trolleyprobleem.'
  },
  {
    id: 93,
    naam: 'Elizabeth Anscombe',
    geboren: 1919,
    overleden: 2001,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'weegschaal'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Passer-idee en leg 1 boek als je Wittgenstein hebt.',
    citaat: 'De intentie bepaalt de handeling.'
  },
  {
    id: 94,
    naam: 'Frantz Fanon',
    geboren: 1925,
    overleden: 1961,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal'],
    vp: 7,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 Spiegel-ideeen en verwijder 1 idee van een medespeler.',
    citaat: 'Elke generatie moet haar missie ontdekken.'
  },
  {
    id: 95,
    naam: 'Antonio Gramsci',
    geboren: 1891,
    overleden: 1937,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart. Pak 1 Weegschaal-idee.',
    citaat: 'De oude wereld sterft en de nieuwe worstelt om geboren te worden.'
  },
  {
    id: 96,
    naam: 'Rosa Luxemburg',
    geboren: 1871,
    overleden: 1919,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 5,
    vaardigheden: ['S', 'Sp'],
    kosten: ['weegschaal'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler filosofen aanspeelt, mag jij 1 idee uit de voorraad pakken.',
    citaat: 'Vrijheid is altijd de vrijheid van de andersdenkende.'
  },
  {
    id: 97,
    naam: 'Confucius',
    geboren: -551,
    overleden: -479,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 7,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 7,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op elke filosoof in deze rij.',
    citaat: 'De edele mens eist van zichzelf, de kleine mens eist van anderen.'
  },
  {
    id: 98,
    naam: 'Laozi',
    geboren: -601,
    overleden: -531,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 7,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer'],
    vp: 4,
    boek_capaciteit: 1,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 idee van jezelf en pak 2 andere ideeen.',
    citaat: 'De reis van duizend mijl begint met een enkele stap.'
  },
  {
    id: 99,
    naam: 'Zhuangzi',
    geboren: -369,
    overleden: -286,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'spiegel'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Verwissel 2 filosofen op je bord van positie.',
    citaat: 'Droom ik dat ik een vlinder ben, of droomt de vlinder dat hij mij is?'
  },
  {
    id: 100,
    naam: 'Nagarjuna',
    geboren: 150,
    overleden: 250,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 6,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder alle ideeen van 1 type. Pak evenveel ideeen van een ander type.',
    citaat: 'Leegte is niet niets; leegte is het ontbreken van inherent bestaan.'
  },
  {
    id: 101,
    naam: 'Al-Kindi',
    geboren: 801,
    overleden: 873,
    stroming: 'Middeleeuwen',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['oog'],
    vp: 3,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee uit de voorraad.',
    citaat: 'We moeten niet beschaamd zijn de waarheid te erkennen, uit welke bron ze ook komt.'
  },
  {
    id: 102,
    naam: 'Al-Farabi',
    geboren: 872,
    overleden: 950,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'passer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee en trek 1 kaart als je een Oudheid-filosoof hebt.',
    citaat: 'De deugdzame stad.'
  },
  {
    id: 103,
    naam: 'Avicenna (Ibn Sina)',
    geboren: 980,
    overleden: 1037,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'oog', 'passer'],
    vp: 8,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee van elk van 2 verschillende typen.',
    citaat: 'De ziel is onsterfelijk.'
  },
  {
    id: 104,
    naam: 'Al-Ghazali',
    geboren: 1058,
    overleden: 1111,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'weegschaal'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 kaart uit de open rij en pak 2 ideeen.',
    citaat: 'De twijfel is de sleutel tot kennis.'
  },
  {
    id: 105,
    naam: 'Giordano Bruno',
    geboren: 1548,
    overleden: 1600,
    stroming: 'Renaissance',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'oog'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Pak 2 Sfeer-ideeen uit de voorraad.',
    citaat: 'Het universum is oneindig.'
  },
  {
    id: 106,
    naam: 'Galileo Galilei',
    geboren: 1564,
    overleden: 1642,
    stroming: 'Renaissance',
    traditie: 'empirisch',
    invloed: 7,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 Oog-ideeen uit de voorraad.',
    citaat: 'En toch beweegt zij.'
  },
  {
    id: 107,
    naam: 'Jeremy Bentham',
    geboren: 1748,
    overleden: 1832,
    stroming: 'Verlichting',
    traditie: 'normatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'passer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Tel alle boeken. Pak 1 idee per 3 boeken.',
    citaat: 'Het grootste geluk voor het grootste aantal.'
  },
  {
    id: 108,
    naam: 'Harriet Taylor Mill',
    geboren: 1807,
    overleden: 1858,
    stroming: 'Feminisme',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Als J.S. Mill in je Academie ligt, trek 2 kaarten. Anders trek 1.',
    citaat: 'Gelijkheid kent geen uitzonderingen.'
  },
  {
    id: 109,
    naam: 'Ralph Waldo Emerson',
    geboren: 1803,
    overleden: 1882,
    stroming: 'Pragmatisme',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'sfeer'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Spiegel-idee en leg 1 boek.',
    citaat: 'Vertrouw op jezelf.'
  },
  {
    id: 110,
    naam: 'Henry David Thoreau',
    geboren: 1817,
    overleden: 1862,
    stroming: 'Pragmatisme',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel'],
    vp: 3,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee naar keuze als je minder dan 3 ideeen hebt.',
    citaat: 'De massa leidt een leven van stille wanhoop.'
  },
  {
    id: 111,
    naam: 'Georg Simmel',
    geboren: 1858,
    overleden: 1918,
    stroming: 'Kritische Theorie',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'oog'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee voor elke unieke stroming in je Academie (max 3).',
    citaat: 'De vreemdeling is geen wandelaar die vandaag komt en morgen gaat.'
  },
  {
    id: 112,
    naam: 'Max Weber',
    geboren: 1864,
    overleden: 1920,
    stroming: 'Kritische Theorie',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek en pak 1 Weegschaal-idee.',
    citaat: 'De ijzeren kooi van de bureaucratie.'
  },
  {
    id: 113,
    naam: 'Democritus',
    geboren: -460,
    overleden: -370,
    stroming: 'Oudheid',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['oog'],
    vp: 3,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee uit de voorraad.',
    citaat: 'Alles bestaat uit atomen en leegte.'
  },
  {
    id: 114,
    naam: 'Empedocles',
    geboren: -494,
    overleden: -434,
    stroming: 'Oudheid',
    traditie: 'contemplatief',
    invloed: 3,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer'],
    vp: 3,
    boek_capaciteit: 1,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 willekeurig idee uit de Bibliotheek.',
    citaat: 'Vier elementen vormen de wortels van alle dingen.'
  },
  {
    id: 115,
    naam: 'Xenophanes',
    geboren: -570,
    overleden: -475,
    stroming: 'Oudheid',
    traditie: 'empirisch',
    invloed: 3,
    vaardigheden: ['L', 'Sp'],
    kosten: [],
    vp: 1,
    boek_capaciteit: 1,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 willekeurig idee.',
    citaat: 'Als ossen goden hadden, zouden ze eruitzien als ossen.'
  },
  {
    id: 116,
    naam: 'Protagoras',
    geboren: -490,
    overleden: -420,
    stroming: 'Oudheid',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['Sp'],
    kosten: ['spiegel'],
    vp: 3,
    boek_capaciteit: 0,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler een filosoof aanspeelt, mag jij 1 idee herruilen met de Bibliotheek.',
    citaat: 'De mens is de maat van alle dingen.'
  },
  {
    id: 117,
    naam: 'Gorgias',
    geboren: -485,
    overleden: -380,
    stroming: 'Oudheid',
    traditie: 'empirisch',
    invloed: 3,
    vaardigheden: ['Sp'],
    kosten: [],
    vp: 2,
    boek_capaciteit: 0,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart uit de open rij.',
    citaat: 'Niets bestaat.'
  },
  {
    id: 118,
    naam: 'Hildegard van Bingen',
    geboren: 1098,
    overleden: 1179,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'oog'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer- en 1 Oog-idee uit de voorraad.',
    citaat: 'De ziel is de groene levenskracht van het lichaam.'
  },
  {
    id: 119,
    naam: 'Christine de Pizan',
    geboren: 1364,
    overleden: 1430,
    stroming: 'Middeleeuwen',
    traditie: 'normatief',
    invloed: 3,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op deze kaart en trek 1 kaart.',
    citaat: 'Als vrouwen de wetten hadden gemaakt, zou de wereld er anders uitzien.'
  },
  {
    id: 120,
    naam: 'Nicolaus Cusanus',
    geboren: 1401,
    overleden: 1464,
    stroming: 'Renaissance',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee. Als je 3+ Sfeer-ideeen hebt, citeer 1 kaart.',
    citaat: 'Geleerde onwetendheid.'
  },
  {
    id: 121,
    naam: 'Ibn Khaldun',
    geboren: 1332,
    overleden: 1406,
    stroming: 'Middeleeuwen',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'weegschaal'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee en leg 1 boek.',
    citaat: 'Geschiedenis is een wetenschap die de oorzaken van gebeurtenissen zoekt.'
  },
  {
    id: 122,
    naam: 'Anne Conway',
    geboren: 1631,
    overleden: 1679,
    stroming: 'Rationalisme',
    traditie: 'contemplatief',
    invloed: 3,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer'],
    vp: 4,
    boek_capaciteit: 1,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee.',
    citaat: 'Alle schepselen zijn van een enkele substantie.'
  },
  {
    id: 123,
    naam: 'Nicolas Malebranche',
    geboren: 1638,
    overleden: 1715,
    stroming: 'Rationalisme',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'oog'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 willekeurig idee en leg 1 boek.',
    citaat: 'Wij zien alle dingen in God.'
  },
  {
    id: 124,
    naam: 'Thomas Reid',
    geboren: 1710,
    overleden: 1796,
    stroming: 'Empirisme',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee.',
    citaat: 'Het gezonde verstand is de basis van alle filosofie.'
  },
  {
    id: 125,
    naam: 'Condorcet',
    geboren: 1743,
    overleden: 1794,
    stroming: 'Verlichting',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Passer-idee en leg 1 boek.',
    citaat: 'De vooruitgang van de menselijke geest is onbeperkt.'
  },
  {
    id: 126,
    naam: 'Olympe de Gouges',
    geboren: 1748,
    overleden: 1793,
    stroming: 'Feminisme',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['S', 'Sp'],
    kosten: ['weegschaal'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler de Schrijven-rij activeert, mag jij 1 boek leggen.',
    citaat: 'De vrouw heeft het recht het schavot te beklimmen; zij moet eveneens het recht hebben het spreekgestoelte te beklimmen.'
  },
  {
    id: 127,
    naam: 'Auguste Comte',
    geboren: 1798,
    overleden: 1857,
    stroming: 'Empirisme',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'passer'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee voor elke filosoof in je Lezen-rij (max 3).',
    citaat: 'Kennen om te voorzien, voorzien om te voorkomen.'
  },
  {
    id: 128,
    naam: 'Harriet Martineau',
    geboren: 1802,
    overleden: 1876,
    stroming: 'Feminisme',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'weegschaal'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart en pak 1 Oog-idee.',
    citaat: 'De beste beveiliging van het geluk is het geven ervan.'
  },
  {
    id: 129,
    naam: 'Max Stirner',
    geboren: 1806,
    overleden: 1856,
    stroming: 'Existentialisme',
    traditie: 'contemplatief',
    invloed: 3,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel'],
    vp: 3,
    boek_capaciteit: 1,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 kaart uit de open rij. Pak 1 idee naar keuze.',
    citaat: 'Ik heb mijn zaak op niets gesteld.'
  },
  {
    id: 130,
    naam: 'Fyodor Dostojevski',
    geboren: 1821,
    overleden: 1881,
    stroming: 'Existentialisme',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'sfeer'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart. Leg 1 boek op deze filosoof.',
    citaat: 'Schoonheid zal de wereld redden.'
  },
  {
    id: 131,
    naam: 'Henri Bergson',
    geboren: 1859,
    overleden: 1941,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee en hergooi de Bibliotheek.',
    citaat: 'De tijd is uitvinding of het is niets.'
  },
  {
    id: 132,
    naam: 'Alfred Jules Ayer',
    geboren: 1910,
    overleden: 1989,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Passer-idee.',
    citaat: 'Een uitspraak is alleen zinvol als ze verifieerbaar is.'
  },
  {
    id: 133,
    naam: 'Gilbert Ryle',
    geboren: 1900,
    overleden: 1976,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'spiegel'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Passer-idee en trek 1 kaart.',
    citaat: 'De geest in de machine.'
  },
  {
    id: 134,
    naam: 'Saul Kripke',
    geboren: 1940,
    overleden: 2022,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'passer'],
    vp: 7,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 2 Passer-ideeen. Als je 3+ Passer-ideeen hebt, citeer 1 kaart.',
    citaat: 'Naamgeving en noodzakelijkheid.'
  },
  {
    id: 135,
    naam: 'Hilary Putnam',
    geboren: 1926,
    overleden: 2016,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwissel 1 idee met de Bibliotheek en pak 1 extra idee.',
    citaat: 'Betekenissen zitten niet in het hoofd.'
  },
  {
    id: 136,
    naam: 'Donald Davidson',
    geboren: 1917,
    overleden: 2003,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart als je 2+ filosofen in de Lezen-rij hebt.',
    citaat: 'Anomalous monisme.'
  },
  {
    id: 137,
    naam: 'Thomas Kuhn',
    geboren: 1922,
    overleden: 1996,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'passer'],
    vp: 7,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Verwijder de huidige Paradigmaverschuiving-tegel en onthul een nieuwe.',
    citaat: 'De structuur van wetenschappelijke revoluties.'
  },
  {
    id: 138,
    naam: 'Daniel Dennett',
    geboren: 1942,
    overleden: 2024,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee. Kijk naar de bovenste 2 kaarten, houd er 1.',
    citaat: 'Het bewustzijn verklaard.'
  },
  {
    id: 139,
    naam: 'Noam Chomsky',
    geboren: 1928,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 6,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'weegschaal'],
    vp: 7,
    boek_capaciteit: 4,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler de Lezen-rij activeert, mag jij 1 Passer-idee pakken.',
    citaat: 'Kleurloos groene ideeen slapen woedend.'
  },
  {
    id: 140,
    naam: 'Cornel West',
    geboren: 1953,
    overleden: null,
    stroming: 'Pragmatisme',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler spreekt, mag jij 1 kaart trekken.',
    citaat: 'Rechtvaardigheid is hoe liefde eruitziet in het openbaar.'
  },
  {
    id: 141,
    naam: 'bell hooks',
    geboren: 1952,
    overleden: 2021,
    stroming: 'Feminisme',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Spiegel-idee voor elke vrouwelijke filosoof (max 3).',
    citaat: 'Liefde is een daad van moed.'
  },
  {
    id: 142,
    naam: 'Gayatri Spivak',
    geboren: 1942,
    overleden: null,
    stroming: 'Postmodernisme',
    traditie: 'dialectisch',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'passer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart en pak 1 Spiegel-idee.',
    citaat: 'Kan de subaltern spreken?'
  },
  {
    id: 143,
    naam: 'Edward Said',
    geboren: 1935,
    overleden: 2003,
    stroming: 'Postmodernisme',
    traditie: 'dialectisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'oog'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Verwijder 1 kaart uit de open rij en citeer die.',
    citaat: 'Het Oosten is een uitvinding van het Westen.'
  },
  {
    id: 144,
    naam: 'Charles Taylor',
    geboren: 1931,
    overleden: null,
    stroming: 'Fenomenologie',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Spiegel-idee en leg 1 boek.',
    citaat: 'Erkenning is een menselijke basisbehoefte.'
  },
  {
    id: 145,
    naam: 'Alasdair MacIntyre',
    geboren: 1929,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee voor elke filosoof uit dezelfde stroming in je Academie.',
    citaat: 'Na de deugd.'
  },
  {
    id: 146,
    naam: 'Michael Sandel',
    geboren: 1953,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler de Spreken-rij activeert, pak 1 Weegschaal-idee.',
    citaat: 'Wat is het juiste om te doen?'
  },
  {
    id: 147,
    naam: 'Amartya Sen',
    geboren: 1933,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'oog'],
    vp: 7,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee voor elke unieke vaardigheidsrij met filosofen.',
    citaat: 'Ontwikkeling als vrijheid.'
  },
  {
    id: 148,
    naam: 'Kwame Anthony Appiah',
    geboren: 1954,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'weegschaal'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 idee voor elke unieke stroming in je Academie (max 2).',
    citaat: 'Kosmopolitisme: ethiek in een wereld van vreemden.'
  },
  {
    id: 149,
    naam: 'Luce Irigaray',
    geboren: 1930,
    overleden: null,
    stroming: 'Feminisme',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Spiegel-idee en trek 1 kaart.',
    citaat: 'Dit geslacht dat niet een is.'
  },
  {
    id: 150,
    naam: 'Julia Kristeva',
    geboren: 1941,
    overleden: null,
    stroming: 'Postmodernisme',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'passer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart en pak 1 Passer-idee.',
    citaat: 'Vreemden voor onszelf.'
  },
  {
    id: 151,
    naam: 'Donna Haraway',
    geboren: 1944,
    overleden: null,
    stroming: 'Feminisme',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'spiegel'],
    vp: 6,
    boek_capaciteit: 2,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Pak 1 Oog- en 1 Spiegel-idee.',
    citaat: 'Het Cyborg Manifesto.'
  },
  {
    id: 152,
    naam: 'Gianni Vattimo',
    geboren: 1936,
    overleden: 2023,
    stroming: 'Postmodernisme',
    traditie: 'contemplatief',
    invloed: 3,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'spiegel'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee en leg 1 boek.',
    citaat: 'Het zwakke denken.'
  },
  {
    id: 153,
    naam: 'Richard Swinburne',
    geboren: 1934,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'contemplatief',
    invloed: 3,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee als je minstens 1 Middeleeuwen-filosoof hebt.',
    citaat: 'Het bestaan van God.'
  },
  {
    id: 154,
    naam: 'Alvin Plantinga',
    geboren: 1932,
    overleden: null,
    stroming: 'Analytische Filosofie',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 6,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee en citeer 1 kaart als je Anselmus hebt.',
    citaat: 'God en andere geesten.'
  },
  {
    id: 155,
    naam: 'Willard Van Orman Quine',
    geboren: 1908,
    overleden: 2000,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'oog'],
    vp: 7,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Hergooi de Bibliotheek en pak 2 Passer-ideeen.',
    citaat: 'Twee dogma\'s van het empirisme.'
  },
  {
    id: 156,
    naam: 'Byung-Chul Han',
    geboren: 1959,
    overleden: null,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'oog'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Alle spelers verliezen 1 boek. Jij legt 1 boek.',
    citaat: 'De vermoeide samenleving.'
  },
  {
    id: 157,
    naam: 'Giorgio Agamben',
    geboren: 1942,
    overleden: null,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'sfeer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart en pak 1 Weegschaal-idee.',
    citaat: 'Homo sacer: de uitzonderingstoestand.'
  },
  {
    id: 158,
    naam: 'Bruno Latour',
    geboren: 1947,
    overleden: 2022,
    stroming: 'Postmodernisme',
    traditie: 'empirisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['oog', 'spiegel'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee en verplaats 1 filosoof naar een andere rij.',
    citaat: 'Wij zijn nooit modern geweest.'
  },
  {
    id: 159,
    naam: 'Alain Badiou',
    geboren: 1937,
    overleden: null,
    stroming: 'Kritische Theorie',
    traditie: 'dialectisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['sfeer', 'passer'],
    vp: 6,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee en citeer 1 kaart.',
    citaat: 'De waarheid is een gebeurtenis.'
  },
  {
    id: 160,
    naam: 'Kwame Nkrumah',
    geboren: 1909,
    overleden: 1972,
    stroming: 'Kritische Theorie',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 6,
    boek_capaciteit: 2,
    kracht_type: 'roze',
    kracht: 'Tijdgeest: Wanneer een medespeler een filosoof aanspeelt, pak 1 Weegschaal-idee.',
    citaat: 'Afrika moet zich verenigen.'
  },
  {
    id: 161,
    naam: 'Mencius',
    geboren: -372,
    overleden: -289,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee als je Confucius hebt, anders pak 1 willekeurig idee.',
    citaat: 'De menselijke natuur is van nature goed.'
  },
  {
    id: 162,
    naam: 'Xunzi',
    geboren: -310,
    overleden: -235,
    stroming: 'Oudheid',
    traditie: 'normatief',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['weegschaal', 'spiegel'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Weegschaal-idee en leg 1 boek.',
    citaat: 'De menselijke natuur is van nature slecht; goedheid is het resultaat van bewuste activiteit.'
  },
  {
    id: 163,
    naam: 'Duns Scotus',
    geboren: 1266,
    overleden: 1308,
    stroming: 'Middeleeuwen',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S'],
    kosten: ['sfeer', 'passer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Sfeer-idee en kijk naar de bovenste 2 kaarten.',
    citaat: 'Haecceitas - het dit-zijn van de dingen.'
  },
  {
    id: 164,
    naam: 'Roger Bacon',
    geboren: 1214,
    overleden: 1294,
    stroming: 'Middeleeuwen',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['oog', 'passer'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Oog-idee en leg 1 boek.',
    citaat: 'Ervaring leert meer dan redenering.'
  },
  {
    id: 165,
    naam: 'Tommaso Campanella',
    geboren: 1568,
    overleden: 1639,
    stroming: 'Renaissance',
    traditie: 'normatief',
    invloed: 3,
    vaardigheden: ['L', 'S'],
    kosten: ['weegschaal', 'sfeer'],
    vp: 4,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Leg 1 boek op deze kaart.',
    citaat: 'De Zonnestad.'
  },
  {
    id: 166,
    naam: 'Pico della Mirandola',
    geboren: 1463,
    overleden: 1494,
    stroming: 'Renaissance',
    traditie: 'eclectisch',
    invloed: 4,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'sfeer'],
    vp: 5,
    boek_capaciteit: 1,
    kracht_type: 'wit',
    kracht: 'Bij Aanstelling: Pak 1 idee van elk symbooltype.',
    citaat: 'De mens kan alles worden wat hij wil.'
  },
  {
    id: 167,
    naam: 'Susanne Langer',
    geboren: 1895,
    overleden: 1985,
    stroming: 'Analytische Filosofie',
    traditie: 'empirisch',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['passer', 'spiegel'],
    vp: 5,
    boek_capaciteit: 3,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Trek 1 kaart en pak 1 Passer-idee.',
    citaat: 'Kunst is de schepping van vormen die het menselijk gevoel symboliseren.'
  },
  {
    id: 168,
    naam: 'Edith Stein',
    geboren: 1891,
    overleden: 1942,
    stroming: 'Fenomenologie',
    traditie: 'contemplatief',
    invloed: 4,
    vaardigheden: ['L', 'S'],
    kosten: ['spiegel', 'sfeer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Spiegel-idee. Als je Husserl hebt, pak er 2.',
    citaat: 'Empathie is de brug naar de ander.'
  },
  {
    id: 169,
    naam: 'Wang Yangming',
    geboren: 1472,
    overleden: 1529,
    stroming: 'Renaissance',
    traditie: 'contemplatief',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['spiegel', 'sfeer'],
    vp: 5,
    boek_capaciteit: 2,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Pak 1 Spiegel-idee. Als je 2+ Contemplatieve filosofen hebt, pak er 2.',
    citaat: 'Kennis en handelen zijn een.'
  },
  {
    id: 170,
    naam: 'Umberto Eco',
    geboren: 1932,
    overleden: 2016,
    stroming: 'Postmodernisme',
    traditie: 'eclectisch',
    invloed: 5,
    vaardigheden: ['L', 'S', 'Sp'],
    kosten: ['passer', 'spiegel'],
    vp: 6,
    boek_capaciteit: 4,
    kracht_type: 'bruin',
    kracht: 'Tijdens de beurt: Citeer 1 kaart en trek 1 kaart uit de open rij.',
    citaat: 'De naam van de roos.'
  }
];
